spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/toyChatApp
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update  # 필요에 따라 create, update, none 선택
    show-sql: true  # SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always  # data.sql, schema.sql 실행
