spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate  # 운영 환경에서는 스키마 자동 변경 방지
    show-sql: false  # 운영에서는 보통 비활성화
    properties:
      hibernate:
        format_sql: false
  sql:
    init:
      mode: never  # 운영 환경에서는 SQL 실행 방지

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    org.example.back: WARN
  file:
    name: logs/prod.log